[2024-07-02T20:23:22.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T20:23:22.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:23:20.163478+00:00 [queued]>
[2024-07-02T20:23:22.343+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:23:20.163478+00:00 [queued]>
[2024-07-02T20:23:22.344+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T20:23:22.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Executar_Cubo> on 2024-07-02 20:23:20.163478+00:00
[2024-07-02T20:23:22.367+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=413) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-02T20:23:22.368+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Biancoll', 'Executar_Cubo', 'manual__2024-07-02T20:23:20.163478+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/Biancoll.py', '--cfg-path', '/tmp/tmp96jshwtg']
[2024-07-02T20:23:22.369+0000] {standard_task_runner.py:63} INFO - Started process 415 to run task
[2024-07-02T20:23:22.370+0000] {standard_task_runner.py:91} INFO - Job 153: Subtask Executar_Cubo
[2024-07-02T20:23:22.415+0000] {task_command.py:426} INFO - Running <TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:23:20.163478+00:00 [running]> on host dd8042584cf8
[2024-07-02T20:23:22.490+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Biancoll' AIRFLOW_CTX_TASK_ID='Executar_Cubo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T20:23:20.163478+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T20:23:20.163478+00:00'
[2024-07-02T20:23:22.492+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T20:23:22.500+0000] {base.py:84} INFO - Using connection ID 'DataLake' for task execution.
[2024-07-02T20:23:22.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T20:23:22.515+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Biancoll.py", line 7, in cubo_financeiro
    imbaud = Imbaud()
             ^^^^^^^^
  File "/opt/airflow/dags/plugin/Scripts/Salvar_Excel.py", line 8, in __init__
    self.download_path = self.get_downloads_path()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/plugin/Scripts/Salvar_Excel.py", line 17, in get_downloads_path
    connection = BaseHook.get_connection('downloads_path')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `downloads_path` isn't defined
[2024-07-02T20:23:22.530+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Biancoll, task_id=Executar_Cubo, run_id=manual__2024-07-02T20:23:20.163478+00:00, execution_date=20240702T202320, start_date=20240702T202322, end_date=20240702T202322
[2024-07-02T20:23:22.541+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 153 for task Executar_Cubo (The conn_id `downloads_path` isn't defined; 415)
[2024-07-02T20:23:22.585+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T20:23:22.601+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:23:22.604+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
