[2024-07-02T20:35:36.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T20:35:36.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:35:34.266805+00:00 [queued]>
[2024-07-02T20:35:36.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:35:34.266805+00:00 [queued]>
[2024-07-02T20:35:36.075+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T20:35:36.087+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Executar_Cubo> on 2024-07-02 20:35:34.266805+00:00
[2024-07-02T20:35:36.094+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=590) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-02T20:35:36.095+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Biancoll', 'Executar_Cubo', 'manual__2024-07-02T20:35:34.266805+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/Biancoll.py', '--cfg-path', '/tmp/tmpporo6a9p']
[2024-07-02T20:35:36.096+0000] {standard_task_runner.py:63} INFO - Started process 592 to run task
[2024-07-02T20:35:36.096+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask Executar_Cubo
[2024-07-02T20:35:36.136+0000] {task_command.py:426} INFO - Running <TaskInstance: Biancoll.Executar_Cubo manual__2024-07-02T20:35:34.266805+00:00 [running]> on host dd8042584cf8
[2024-07-02T20:35:36.212+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Biancoll' AIRFLOW_CTX_TASK_ID='Executar_Cubo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T20:35:34.266805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T20:35:34.266805+00:00'
[2024-07-02T20:35:36.214+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T20:35:36.223+0000] {base.py:84} INFO - Using connection ID 'DataLake' for task execution.
[2024-07-02T20:35:36.229+0000] {base.py:84} INFO - Using connection ID 'Dowload' for task execution.
[2024-07-02T20:35:36.241+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T20:35:36.242+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Biancoll.py", line 8, in cubo_financeiro
    imbaud.salvar_excel()
  File "/opt/airflow/dags/plugin/Scripts/Salvar_Excel.py", line 21, in salvar_excel
    df = pd.read_parquet(arquivo)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '{"path": "C:\\Users\\gabri\\OneDrive\\Data Analytics\\03 - DataLake"}/Comparin/01-Imbaud/vendas.parquet'
[2024-07-02T20:35:36.261+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Biancoll, task_id=Executar_Cubo, run_id=manual__2024-07-02T20:35:34.266805+00:00, execution_date=20240702T203534, start_date=20240702T203536, end_date=20240702T203536
[2024-07-02T20:35:36.275+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 158 for task Executar_Cubo ([Errno 2] No such file or directory: '{"path": "C:\\Users\\gabri\\OneDrive\\Data Analytics\\03 - DataLake"}/Comparin/01-Imbaud/vendas.parquet'; 592)
[2024-07-02T20:35:36.311+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T20:35:36.324+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:35:36.328+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
