[2024-07-02T11:48:29.395+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Implemaster.Extrair_Dados scheduled__2024-06-06T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
